
learning:
  algorithm:
    class_name: TDO
    clip_param: 0.2
    desired_kl: 0.01
    entropy_coef: 0.01
    gamma: 0.99
    lam: 0.95
    learning_rate: 0.001
    max_grad_norm: 1.0
    num_learning_epochs: 5
    num_mini_batches: 4
    schedule: adaptive
    use_clipped_value_loss: true
    value_loss_coef: 1.0
    td_entropy_coef: 0.0
    return_boosting_coef: 0.0
    action_noise_threshold: 0.0
  policy:
    activation: elu
    actor_hidden_dims:
    - 512
    - 256
    - 128
    class_name: ActorCriticTDO
    critic_hidden_dims:
    - 512
    - 256
    - 128
    init_noise_std: 1.0
  temporal_distribution:
    learning_rate: 0.001
    class_name: TemporalDistribution
  PPO: false
  empirical_normalization: false
  exp_name: null
  num_steps_per_env: 24
  reset_rate: 0.0
  print_infos: true
  record_interval: 50
  save_interval: 100
  seed: 1
  wandb_entity: ziyanx02
  wandb_project: Gait
environment:
  PPO: false
  urdf_path: urdf/leap_hand/leap_hand_right_glb.urdf
  links_to_keep:
  - thumb_fingertip
  - fingertip
  - fingertip_2
  - fingertip_3
  num_actions: 16
  num_dofs: 16
  num_states: 42
  termination_contact_link_names:
  - base
  penalized_contact_link_names:
  - base
  - mcp_joint
  - mcp_joint_2
  - mcp_joint_3
  - thumb_temp_base
  - pip
  - pip_2
  - pip_3
  - thumb_pip
  - dip
  - dip_2
  - dip_3
  - thumb_dip
  feet_link_names:
  - thumb_fingertip
  - fingertip
  - fingertip_2
  - fingertip_3
  body_link_name:
  - base
  PD_stiffness:
    ? ''
    : 40.0
  PD_damping:
    ? ''
    : 1.0
  armature: 0.05
  dof_damping: 0.0
  action_scale: 0.25
  clip_actions: 100.0
  control_freq: 50
  decimation: 4
  delay_action: true
  dof_names:
  - '0'
  - '1'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  episode_length_s: 20.0
  period_length_s: 0.5
  use_timeout: true
  reset_after_termination: true
  termination_if_height_lower_than: 0.0
  termination_if_pitch_greater_than: 0.4
  termination_if_roll_greater_than: 0.4
  base_init_pos:
  - 0.0
  - 0.0
  - 0.24119752645492554
  base_init_quat:
  - 0.7071067690849304
  - 0.0
  - 0.7071068286895752
  - 3.615632238052058e-09
  default_joint_angles:
    '0': 0.
    '1': 0.
    '10': 0.
    '11': 0.
    '12': 0.
    '13': 0.
    '14': 0.
    '15': 0.
    '2': 0.
    '3': 0.
    '4': 0.
    '5': 0.
    '6': 0.
    '7': 0.
    '8': 0.
    '9': 0.
  resampling_time_s: 4.0
  randomize_base_mass: true
  added_mass_range:
  - -1.0
  - 3.0
  randomize_com_displacement: true
  com_displacement_range:
  - -0.01
  - 0.01
  randomize_friction: true
  friction_range:
  - 0.2
  - 1.5
  randomize_kd_scale: true
  kd_scale_range:
  - 0.8
  - 1.2
  randomize_kp_scale: true
  kp_scale_range:
  - 0.8
  - 1.2
  randomize_motor_offset: true
  motor_offset_range:
  - -0.02
  - 0.02
  randomize_motor_strength: false
  motor_strength_range:
  - 0.9
  - 1.1
  pos_randomization: 0.0
  rot_randomization: 0.1
  dof_pos_randomization: 0.3
  max_push_vel_xy: 1.0
  push_interval_s: -1
  command:
    lin_vel_x_range:
    - -1.0
    - 1.0
    lin_vel_y_range:
    - -1.0
    - 1.0
    ang_vel_range:
    - -1.0
    - 1.0
  gait:
    base_height_target: 0.3
    duration:
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    frequency:
    - 2.0
    - 2.0
    - 2.0
    - 2.0
    offset:
    - 0.0
    - 0.5
    - 0.5
    - 0.0
    stationary_position:
    - - 0.15
      - -0.15
    - - 0.15
      - 0.15
    - - -0.15
      - -0.15
    - - -0.15
      - 0.15
    feet_height_target:
    - 0.1
    - 0.1
    - 0.1
    - 0.1
  observation:
    num_obs: 59
    num_priv_obs: 64
    obs_noise:
      ang_vel: 0.1
      dof_pos: 0.01
      dof_vel: 0.1
      gravity: 0.02
    obs_scales:
      ang_vel: 1.0
      dof_pos: 1.0
      dof_vel: 0.05
      lin_vel: 1.0
  reward:
    reward_scales:
      lin_vel: 1.0
      ang_vel: 0.5
      alive: 3.0
      ang_vel_xy: -0.05
      base_height: -30.0
      dof_acc: -0.05
      dof_vel: -0.0
      dof_pos_diff: -0.1
      lin_vel_z: -2.0
      orientation: -5.0
      contact_force: -1.0
      contact_vel: -1.0
      feet_height: -10.0
      feet_pos: -10.0
      action_smoothness_1: -0.5
      action_smoothness_2: -0.5
      torques: -0.0001
    soft_dof_pos_limit: 0.9
    tracking_sigma: 0.25
  robot_scale: 1.0
reward_tuning:
  num_iterations: 3
  num_samples: 4
  num_logpoints: 10
  note: hand grasping movement task
