learning:
  algorithm:
    class_name: TDO
    clip_param: 0.2
    desired_kl: 0.01
    entropy_coef: 0.01
    gamma: 0.99
    lam: 0.95
    learning_rate: 0.001
    max_grad_norm: 1.0
    num_learning_epochs: 5
    num_mini_batches: 4
    schedule: adaptive
    use_clipped_value_loss: true
    value_loss_coef: 1.0
    td_entropy_coef: 0.0
    return_boosting_coef: 0.0
    action_noise_threshold: 0.0
  policy:
    activation: elu
    actor_hidden_dims:
    - 512
    - 256
    - 128
    class_name: ActorCriticTDO
    critic_hidden_dims:
    - 512
    - 256
    - 128
    init_noise_std: 1.0
  temporal_distribution:
    learning_rate: 0.001
    class_name: TemporalDistribution
  PPO: false
  empirical_normalization: false
  exp_name: null
  num_steps_per_env: 24
  reset_rate: 0.0
  print_infos: true
  record_interval: 50
  save_interval: 100
  seed: 1
  wandb_entity: ziyanx02
  wandb_project: Gait
environment:
  PPO: false
  urdf_path: urdf/go2/urdf/go2.urdf
  links_to_keep:
  - FR_foot
  - FL_foot
  - RR_foot
  - RL_foot
  num_actions: 12
  num_dofs: 12
  num_states: 34
  termination_contact_link_names:
  - base
  penalized_contact_link_names:
  - base
  - Head_upper
  - FL_hip
  - FR_hip
  - RL_hip
  - RR_hip
  - imu
  - radar
  - Head_lower
  - FL_thigh
  - FR_thigh
  - RL_thigh
  - RR_thigh
  - FL_calf
  - FR_calf
  - RL_calf
  - RR_calf
  - FL_calflower
  - FR_calflower
  - RL_calflower
  - RR_calflower
  - FL_calflower1
  - FR_calflower1
  - RL_calflower1
  - RR_calflower1
  feet_link_names:
  - FR_foot
  - FL_foot
  - RR_foot
  - RL_foot
  body_link_name:
  - base
  PD_stiffness:
    ? ''
    : 30.0
  PD_damping:
    ? ''
    : 1.5
  armature: 0.05
  dof_damping: 0.0
  action_scale: 0.25
  clip_actions: 100.0
  control_freq: 50
  decimation: 4
  delay_action: true
  dof_names:
  - FL_calf_joint
  - FL_hip_joint
  - FL_thigh_joint
  - FR_calf_joint
  - FR_hip_joint
  - FR_thigh_joint
  - RL_calf_joint
  - RL_hip_joint
  - RL_thigh_joint
  - RR_calf_joint
  - RR_hip_joint
  - RR_thigh_joint
  episode_length_s: 20.0
  period_length_s: 0.5
  use_timeout: true
  reset_after_termination: true
  termination_if_height_lower_than: 0.0
  termination_if_pitch_greater_than: 0.4
  termination_if_roll_greater_than: 0.4
  base_init_pos:
  - 0.0
  - 0.0
  - 0.35357487201690674
  base_init_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  default_joint_angles:
    FL_calf_joint: -1.5
    FL_hip_joint: 0.0
    FL_thigh_joint: 0.8
    FR_calf_joint: -1.5
    FR_hip_joint: 0.0
    FR_thigh_joint: 0.8
    RL_calf_joint: -1.5
    RL_hip_joint: 0.0
    RL_thigh_joint: 1.0
    RR_calf_joint: -1.5
    RR_hip_joint: 0.0
    RR_thigh_joint: 1.0
  resampling_time_s: 4.0
  randomize_base_mass: true
  added_mass_range:
  - -1.0
  - 3.0
  randomize_com_displacement: true
  com_displacement_range:
  - -0.01
  - 0.01
  randomize_friction: true
  friction_range:
  - 0.2
  - 1.5
  randomize_kd_scale: true
  kd_scale_range:
  - 0.8
  - 1.2
  randomize_kp_scale: true
  kp_scale_range:
  - 0.8
  - 1.2
  randomize_motor_offset: true
  motor_offset_range:
  - -0.02
  - 0.02
  randomize_motor_strength: false
  motor_strength_range:
  - 0.9
  - 1.1
  pos_randomization: 0.0
  rot_randomization: 0.1
  dof_pos_randomization: 0.3
  max_push_vel_xy: 1.0
  push_interval_s: -1
  use_terrain: false
  command:
    lin_vel_x_range:
    - -1.0
    - 1.0
    lin_vel_y_range:
    - -1.0
    - 1.0
    ang_vel_range:
    - -1.0
    - 1.0
  gait:
    base_height_target: 0.3295976221561432
    duration:
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    frequency:
    - 2.0
    - 2.0
    - 2.0
    - 2.0
    offset:
    - 0.0
    - 0.5
    - 0.5
    - 0.0
    stationary_position:
    - - 0.2
      - -0.15
    - - 0.2
      - 0.15
    - - -0.2
      - -0.15
    - - -0.2
      - 0.15
    feet_height_target:
    - 0.1318390488624573
    - 0.1318390488624573
    - 0.1318390488624573
    - 0.1318390488624573
  observation:
    num_obs: 49
    num_priv_obs: 64
    obs_noise:
      ang_vel: 0.1
      dof_pos: 0.01
      dof_vel: 0.5
      gravity: 0.02
    obs_scales:
      ang_vel: 1.0
      dof_pos: 1.0
      dof_vel: 0.05
      lin_vel: 1.0
  reward:
    reward_scales:
      lin_vel: 1.0
      ang_vel: 0.5
      alive: 3.0
      ang_vel_xy: -0.05
      base_height: -30.0
      dof_acc: -0.05
      dof_vel: -0.0
      dof_pos_diff: -0.1
      lin_vel_z: -2.0
      orientation: -5.0
      contact_force: -1.0
      contact_vel: -1.0
      feet_height: -10.0
      feet_pos: -10.0
      action_smoothness_1: -0.5
      action_smoothness_2: -0.5
      torques: -0.0001
    soft_dof_pos_limit: 0.9
    tracking_sigma: 0.25
  robot_scale: 1.0
  body_init_pos:
  - 0.0
  - 0.0
  - 0.35357487201690674
  body_init_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
reward_tuning:
  num_iterations: 3
  num_samples: 4
  num_logpoints: 10
  note: walk with four legs
